version: "2"
linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    misspell:
      locale: UK
formatters:
  enable: [gofmt, goimports]
