package cmd

import (
	"bytes"
	"errors"
	"io"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// run executes the root command with a clean flag state and returns STDOUT.
// Cobra flags are package-level variables, so without the reset a value set by
// one test (say --yes) would leak into the next; the reset walks every command
// in the tree, not just the root's persistent flags.
func run(t *testing.T, args ...string) (string, error) {
	t.Helper()
	resetFlags(rootCmd)
	// Tests are never interactive: stdin is whatever the test queued, else empty.
	if testStdin == nil {
		rootCmd.SetIn(strings.NewReader(""))
	} else {
		rootCmd.SetIn(testStdin)
		testStdin = nil
	}
	var out, errOut bytes.Buffer
	rootCmd.SetOut(&out)
	rootCmd.SetErr(&errOut)
	rootCmd.SetArgs(args)
	err := rootCmd.Execute()
	return out.String(), err
}

// testStdin, when set, is consumed by the next run().
var testStdin io.Reader

func resetFlags(c *cobra.Command) {
	reset := func(f *pflag.Flag) {
		// Slice flags append on Set, so "[]" would become a literal element.
		if sv, ok := f.Value.(pflag.SliceValue); ok {
			_ = sv.Replace(nil)
		} else {
			_ = f.Value.Set(f.DefValue)
		}
		f.Changed = false
	}
	c.PersistentFlags().VisitAll(reset)
	c.Flags().VisitAll(reset)
	for _, sub := range c.Commands() {
		resetFlags(sub)
	}
}

func TestVersion_WorksWithoutAnyConfig(t *testing.T) {
	t.Setenv("CLOUD_CONFIG_DIR", t.TempDir())
	out, err := run(t, "version")
	if err != nil {
		t.Fatalf("version must never need config or network: %v", err)
	}
	if !strings.HasPrefix(out, "cloud ") {
		t.Errorf("unexpected output %q", out)
	}
}

func TestBadOutputFormat_IsAUsageError(t *testing.T) {
	t.Setenv("CLOUD_CONFIG_DIR", t.TempDir())
	// `completion` is a built-in command that goes through the persistent pre-run.
	_, err := run(t, "--output", "xml", "completion", "bash")
	if err == nil {
		t.Fatal("an unknown output format must be rejected")
	}
	var u *UsageError
	if !errors.As(err, &u) {
		t.Errorf("want UsageError, got %T: %v", err, err)
	}
	if ExitCode(err) != ExitUsage {
		t.Errorf("exit code = %d, want %d", ExitCode(err), ExitUsage)
	}
}

func TestRetiredAPIHost_IsRefusedAsUsage(t *testing.T) {
	t.Setenv("CLOUD_CONFIG_DIR", t.TempDir())
	t.Setenv("CLOUD_API_URL", "https://swiftcloud.co.zm/api/v1")
	_, err := run(t, "completion", "bash")
	if err == nil {
		t.Fatal("a retired API host must be refused before any command runs")
	}
	if ExitCode(err) != ExitUsage {
		t.Errorf("exit code = %d, want %d (usage)", ExitCode(err), ExitUsage)
	}
	if !strings.Contains(err.Error(), "cloud.co.zm/api/v1") {
		t.Errorf("error should name the replacement URL: %v", err)
	}
}

func TestDefaultsResolveWithNoConfigFile(t *testing.T) {
	t.Setenv("CLOUD_CONFIG_DIR", t.TempDir())
	if _, err := run(t, "completion", "bash"); err != nil {
		t.Fatalf("a fresh machine with no config must work: %v", err)
	}
	if cfg == nil || cfg.APIURL != "https://cloud.co.zm/api/v1" {
		t.Errorf("resolved API URL = %v, want production default", cfg)
	}
}

/*
Help tests. The help is the only documentation most people read, and the thing
it most often fails to say is where a name goes: Cobra lists subcommands by
name alone, so "list <app>" reads as a bare "list" and the reader cannot tell
that "cloud app domain list" needs the app's name. These tests hold that open.
*/

// TestCommandListingShowsArguments guards the usage template override: a parent's
// listing must carry each child's arguments, not just its name.
func TestCommandListingShowsArguments(t *testing.T) {
	for _, tc := range []struct {
		args []string
		want string
	}{
		{[]string{"app", "domain", "--help"}, "list <app>"},
		{[]string{"app", "domain", "--help"}, "add <app> <hostname>"},
		{[]string{"app", "--help"}, "get <name>"},
		{[]string{"app", "--help"}, "create <name> --image <ref>"},
		{[]string{"org", "--help"}, "use <slug>"},
	} {
		out, err := run(t, tc.args...)
		if err != nil {
			t.Fatalf("%v: %v", tc.args, err)
		}
		if !strings.Contains(out, tc.want) {
			t.Errorf("`cloud %s` listing does not show %q:\n%s", strings.Join(tc.args, " "), tc.want, out)
		}
	}
}

// TestEveryRunnableCommandHasAnExample keeps new commands from shipping without
// one; an example is what tells a reader the argument order.
func TestEveryRunnableCommandHasAnExample(t *testing.T) {
	var missing []string
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		generated := strings.Contains(c.CommandPath(), "completion")
		switch {
		case generated, c.Name() == "help", c.Name() == "version", c == rootCmd:
			// Generated by Cobra, trivial, or covered by the root's own examples.
		case c.Example == "":
			missing = append(missing, c.CommandPath())
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(rootCmd)
	if len(missing) > 0 {
		t.Errorf("commands without an Example block: %s", strings.Join(missing, ", "))
	}
}

// TestExamplesAreRunnableShapes catches the copy-paste failure that makes an
// example worse than none: a flag or subcommand the tree does not have.
func TestExamplesAreRunnableShapes(t *testing.T) {
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, line := range strings.Split(c.Example, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			// Strip a trailing prose column ("cloud whoami   who am I") and env prefixes.
			fields := strings.Fields(line)
			for len(fields) > 0 && strings.Contains(fields[0], "=") {
				fields = fields[1:]
			}
			if len(fields) == 0 || fields[0] == "echo" || fields[0] != "cloud" {
				continue
			}
			cmd, _, err := rootCmd.Find(fields[1:])
			if err != nil {
				t.Errorf("%s: example %q does not resolve to a command: %v", c.CommandPath(), line, err)
				continue
			}
			for _, f := range fields[1:] {
				if !strings.HasPrefix(f, "--") {
					continue
				}
				name := strings.TrimPrefix(strings.SplitN(f, "=", 2)[0], "--")
				if cmd.Flags().Lookup(name) == nil && cmd.InheritedFlags().Lookup(name) == nil && rootCmd.PersistentFlags().Lookup(name) == nil {
					t.Errorf("%s: example %q uses unknown flag --%s", c.CommandPath(), line, name)
				}
			}
		}
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(rootCmd)
}
